### ISSUE TITLE
#managing-repos-part-2 (github tooling helper)

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/tooling-helpers#58]
Split out the github tooling helper into its own project

https://github.com/Financial-Times/tooling-helpers

* Github helper and CLI into its own repo
* CircleCI setup
* Publishing on npm

**Comment by adambraimbridge** [comment]
TODO: Pull requests

- [ ] Remove GitHub helper

**Comment by adambraimbridge** [comment]
@Financial-Times/etg: Now's your chance to sanity-check this repository before I publish it to NPM.

**Comment by simonplend** [comment]
@adambraimbridge 

- `monorepo.json` should be removed - it doesn't apply here
- Relative links in the `README` won't work when the package is published to know (I know we discussed this earlier, so you probably already have local changes for this!)
- If we think Secret Squirrel instils a false sense of security, why is this repository using it? If we must use it, it might be an idea to put the config for Husky in its own config file, rather than hiding it away in `package.json`: https://github.com/typicode/husky#upgrading-from-014

**Comment by adambraimbridge** [comment]
Closing this as it's as good as done.
